### ISSUE TITLE
Rename the frame

### ISSUE THREAD

**Issue by vasilvv** [quicwg/reliable-stream-reset#10]
As far as I remember, "reliable reset" originally referred to the fact that this feature would make WebTransport stream resets reliable.  However, outside of that context, that name does not make that much sense, since QUIC resets are already reliable.

**Comment by marten-seemann** [comment]
As discussed in Yokohama, this is the plan for the next revision of the document.

**Comment by marten-seemann** [comment]
Resolved by #11.
