### ISSUE TITLE
What is the main value add of CLOSE_STREAM / RELIABLE_RESET?

### ISSUE THREAD

**Issue by ProjectsByJackHe** [quicwg/reliable-stream-reset#25]
While implementing this SPEC for MsQuic, I've had to develop some non-trivial book-keeping mechanisms so the sender / receiver can abort their send/recv paths at the appropriate times. 

In the context of the core use case, an implementation could be made much simpler if the sender just re-uses the RESET frame abortive path once it has sent / ACKed enough data. Receiver doesn't need to know or do anything.

That way, the sender doesn't necessarily even need to communicate a RELIABLE RESET to the receiver, it'll just be a more appropriately timed RESET, and perhaps the ReliableSize could be something communicated / negotiated during the handshake, or as an added field in STREAM_STARTED frame or something?

**Comment by marten-seemann** [comment]
Is there any (editorial) clarification that could make the text in the draft any clearer, @ProjectsByJackHe?

**Comment by ProjectsByJackHe** [comment]
> Is there any (editorial) clarification that could make the text in the draft any clearer, @ProjectsByJackHe?

Perhaps changing the name of CLOSE_STERAM frame to RESET_RELIABLE frame?

**Comment by kazuho** [comment]
@ProjectsByJackHe 
> Also, as a noobie in QUIC / networking, some more details on state transitions (should we have a brand new state RESET_RELIABLE, RESET_RELIABLE_ACKED, or just re-use the existing ones after a state transition) would be helpful.

I think my +1 goes to adding implementation guidance.

IMO it would make sense to clarify that one way of implementing this extension is to treat CLOSE_STREAM as a variant of FIN where the bytes that need to be sent before transiting from Data Sent to Data Rcvd (or from Size Known to Data Rcvd) is different than the final offset.

**Comment by marten-seemann** [comment]
@kazuho Would you mind sending a PR?
