### ISSUE TITLE
Applications might require that the Reliable Size not reduce

### ISSUE THREAD

**Issue by martinthomson** [quicwg/reliable-stream-reset#63]
In Section 5.1, should this say something like:

> While multiple RESET_STREAM_AT frames can reduce Reliable Size, some applications might need to ensure that a minimum amount of data is always delivered on a stream.  Application protocols can establish rules for streams that ensure that Reliable Size is not reduced below a certain threshold if that is necessary to ensure correct operation of the protocol.

To explicitly signal this WebTransport, as it were.

**Comment by marten-seemann** [comment]
How would an application enforce this, without reaching deep down into the QUIC layer?

**Comment by martinthomson** [comment]
I'm not thinking about enforcement, just a "if you implement this protocol and you reset a stream (or a particular type of stream), you MUST use RESET_STREAM_AT and not set Reliable Size less than X".

**Comment by marten-seemann** [comment]
Makes sense. I think we can apply your suggestion, although I believe that even if we don't, applications can still impose this kind of requirement.

**Comment by DavidSchinazi** [comment]
Nothing in the current document prevents applications from doing this, but explicitly mentioning that it's possible is a good idea. So +1 to MT's suggestion.

**Comment by huitema** [comment]
I think the initial goal is to protect the web transport header when the WT application "resets" a stream. I would implement that in the WT API itself, so that a bare API level "Reset" always map to a "RESET AT <after the WT header>".
