### ISSUE TITLE
Remove the "reliable reset" phrasing from the draft

### ISSUE THREAD

**Issue by vasilvv** [quicwg/reliable-stream-reset#64]
Resets are always reliable in QUIC itself, so the phrasing is in general confusing.  We already renamed the frame to RESET_STREAM_AT, so the rest of the draft should probably be updated too.

**Comment by marten-seemann** [comment]
Can you point me to where you think the phrasing is confusing? Do you mean the name of the Markdown file? We could rename it, but I don't think that matters for the RFC.

As far as I can see, the draft doesn't contain the words "reliable reset" anymore.

**Comment by marten-seemann** [comment]
Do you mean the title of the document? I'm wondering what a better title would be. Any suggestions?

**Comment by LPardue** [comment]
We don't need to change the filename.

As far as title alternatives, perhaps "QUIC Stream Resets with Guaranteed Delivery"

**Comment by martinthomson** [comment]
I agree with Victor and was going to open a similar message.  "Guaranteed" is not in fact guaranteed.  The sender can just set the amount to zero at any time. 

Similarly, the value implied by "Reliable Size" is not reliable.

Instead, I would suggest "Delivered Size" or "Retained Size", with a slight preference for the latter, but I would be happy to entertain other suggestions.  That suggests "QUIC Stream Resets with Retained Data".

**Comment by kazuho** [comment]
Or maybe "QUIC Stream Resets with Data Delivery."

**Comment by marten-seemann** [comment]
Any objections to calling it partial reliability?

**Comment by kazuho** [comment]
Yeah I think it would be better to have a title that is technically correct; I'd rather not see people arguing this is not what they perceive as "partial reliability."

**Comment by marten-seemann** [comment]
Discussed with @kazuho OOB. It's a kind of partial reliability, and we won't be claiming anything incorrect as long as we don't claim to present an all-encompassing solution for partial reliability.

For example, "QUIC Stream Resets with Partially Reliable Stream Data Delivery" would be a possible title.
